-- Daily Challenge : SQL Puzzle
-- Q1: 
-- The output will be "0" because you are comparing null inside the IN statment.
-- Q2:
-- The output will be 2 because there are two values in column "id" in table "FirstTab" that are not "5".
-- Q3:
-- The output will be 0 because there is null in SecondTab.
-- Q4:
-- The output will be 2 because there are two values in FirstTab which are not null or 5.